### ISSUE TITLE
Cocoapods - Not building, 331 issues

### ISSUE THREAD

**Issue by cmontanya** [finn-no/charcoal-ios#353]
Hi, 
I have just created a new app to test the cocoa pods install of charcoal, and it is not working:

1) this does not work in pod install:
pod 'Charcoal'

2) this does not work in pod install:
pod 'Charcoal/FINN'

3) this does works in pod install:
pod "Charcoal", git: "https://github.com/finn-no/charcoal-ios.git"

However when trying to build the process fails with over 300 issues:
<img width="261" alt="CleanShot 2020-11-14 at 15 03 10@2x" src="https://user-images.githubusercontent.com/74181118/99150167-96117180-268a-11eb-8dfe-00bbdaa84184.png">

![CleanShot 2020-11-14 at 15 04 25@2x](https://user-images.githubusercontent.com/74181118/99150194-b5a89a00-268a-11eb-9ca5-01b4661ac562.png)

**Comment by lernamanto** [comment]
same here!
have a version installed using Carthage, but would really like to use cocoa pods, can you please help!!

This library is amazing, very easy to use and looks great, would be perfect if the install wasn't such a pain...

**Comment by osanoj** [comment]
Hi!

We do not publish our pod to cocoapods trunk so you will need to include the git url yes.

This repo also depends on our FinniversKit framework, so try adding `pod "FinniversKit", git: "https://github.com/finn-no/FinniversKit"` and see if that helps.

Really glad you like Charcoal, may I ask for what and how you want to use it yourself? It would be very interesting to know.

**Comment by lernamanto** [comment]
Hi!

I tried to do as you advised, adding the pod "FinniversKit", git: "https://github.com/finn-no/FinniversKit" in my podfile but now pod install won't work anymore?

![CleanShot 2020-11-16 at 10 45 27](https://user-images.githubusercontent.com/4980901/99243833-21a91080-27f9-11eb-914b-3d47bce21269.png)

**Comment by osanoj** [comment]
Then it seems you have an old version in your `Podfile.lock`. Try `pod update FinniversKit`.

**Comment by lernamanto** [comment]
Hi!,
First of all just want to thank you for your prompt responses, forgot to mention it in previous messages so now doing it straight away.

Really appreciate the time you're putting into this to help!


Ok, I've done as you advised and and now it's much better, only 4 issues left down from over 300!

Here they are:

![CleanShot 2020-11-17 at 14 05 24](https://user-images.githubusercontent.com/4980901/99399756-fe0bc600-28dd-11eb-853c-273413c889d0.png)


![CleanShot 2020-11-17 at 14 10 15](https://user-images.githubusercontent.com/4980901/99400244-a1f57180-28de-11eb-9aca-4ece430863cc.png)

**Comment by lernamanto** [comment]
?

**Comment by osanoj** [comment]
Not sure, but we maybe have an issue of what is added to the FINN specific pod `(pod "Charcoal/FINN", git: "https://github.com/finn-no/charcoal-ios.git"`) and what is in the core Charcoal pod. It should be possible to use `pod "Charcoal", git: "https://github.com/finn-no/charcoal-ios.git"`, but perhaps not now then? 🤔 

Which one are you trying to use? If you want to try how things work cloning the repo and using the Demo is probably best. Or what are you trying to do?

**Comment by lernamanto** [comment]
Hi,
so I have an app where I installed charcoal using Carthage. Everything used to work fine up to Xcode 12.1, until the latest version of Xcode came out, Xcode 12.2.
Since then when trying to build my app I get this error message:
![CleanShot 2020-12-08 at 13 04 55](https://user-images.githubusercontent.com/4980901/101487382-02178a80-3956-11eb-8bdb-f3a6e1cbd6b4.png)

I imagine this will go away once you will have updated everything for the latest Xcode version.

However in my app every library I use is installed with CocoaPods, and I use Carthage exclusively for Charcoal, because installing it with Cocoapods does not work.

It would be great to solve the issue with Charcoal and Cocoapods, so I can add it the same way I do with my other libraries, and remove Carthage altogether.

Initially I though the problem might be in my app, maybe some settings that would cause issues with Charcoal, but I have since created completely new projects, with just Charcoal in them installed using Cocoapods and those do not build and are full of errors (as per my previous messages).

I just did it again now, there are the steps:

1) In Xcode create a new project, single application (Storyboard, UIKIt and App Delegate)

2) Build and run the project, an app with a white screen runs fine both on simulator and on a physical device

3) Close Xcode

4) Add a pod file in the project folder with in it a single pod, Charcoal:
 pod "Charcoal", git: "https://github.com/finn-no/charcoal-ios.git"

5) run pod install

6) open the workspace file and try to build the app. 

The app does not build anymore and these error are now present:

![CleanShot 2020-12-08 at 13 12 45](https://user-images.githubusercontent.com/4980901/101488117-14de8f00-3957-11eb-831e-08bb27fcdb5d.png)

![CleanShot 2020-12-08 at 13 13 05](https://user-images.githubusercontent.com/4980901/101488153-21fb7e00-3957-11eb-95bc-fd096942edb8.png)

7) Close Xcode again

8) Open the Podfile and add this line:
pod "FinniversKit", git: "https://github.com/finn-no/FinniversKit"

9) run pod update FinniversKit

10) Open the project and try to build it again.
The app does not build anymore and these error are now present:

![CleanShot 2020-12-08 at 13 17 31](https://user-images.githubusercontent.com/4980901/101488621-be258500-3957-11eb-90e1-6e4c7480ad15.png)


Can you please help me with this? 
Thank you

**Comment by lernamanto** [comment]
Update:

Managed to have it working by using this in the podfile:
pod "FinniversKit", git: "https://github.com/finn-no/FinniversKit"
pod "Charcoal/FINN", git: "https://github.com/finn-no/charcoal-ios.git"

so instead of pod "Charcoal", git: "https://github.com/finn-no/charcoal-ios.git" I now use pod "Charcoal/FINN", git: "https://github.com/finn-no/charcoal-ios.git" and it works fine.

Hope will help anybody having the same issue 🙂
